version: "3.8"

services:
  rpg-api:
    image: definya/definya-team:api-latest
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5002"]
      interval: 60s
      timeout: 30s
      retries: 3
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.api == true
        preferences:
          - spread: node.id
        max_replicas_per_node: 1
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 2
        delay: 10s
      labels:
        # Basic setup for API config
        - traefik.enable=true
        - traefik.http.routers.rpg-api.rule=Host(`na.definya.com`)
        - traefik.http.routers.rpg-api.entrypoints=websecure
        - traefik.http.routers.rpg-api.tls.certresolver=myresolver
        - traefik.http.services.rpg-api-service.loadbalancer.server.port=5002
        - traefik.http.routers.rpg-api.service=rpg-api-service

        # Websockets
        - traefik.http.routers.rpg-api-socket.rule=Host(`na.definya.com`) && Path(`/socket.io/`)
        - traefik.http.routers.rpg-api-socket.entrypoints=websecure
        - traefik.http.routers.rpg-api-socket.tls.certresolver=myresolver
        - traefik.http.services.rpg-api-socket-service.loadbalancer.server.port=5101
        - traefik.http.routers.rpg-api-socket.service=rpg-api-socket-service

        # #  Add sticky session for websockets
        #! Careful because when combined with multi client, this will lead all MC characters to be connected to the same server, compromising load balancer
        # - "traefik.http.services.rpg-api-socket-service.loadbalancer.sticky=true"
        # - "traefik.http.services.rpg-api-socket-service.loadbalancer.sticky.cookie.name=StickyCookie"
        # - "traefik.http.services.rpg-api-socket-service.loadbalancer.sticky.cookie.secure=true"

    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      FORCE_COLOR: "true"
      NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
      NEW_RELIC_APP_NAME: "Definya API"
    networks:
      - rpg-network

  rpg-pathfinder:
    image: definya/definya-team:rpg-pathfinder-latest
    environment:
      GO111MODULE: "on"
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.api == true
        preferences:
          - spread: node.id
        max_replicas_per_node: 1
    networks:
      - rpg-network

  rpg-client:
    image: definya/definya-team:client-latest
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 120s
      timeout: 10s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rpg-client.rule=Host(`play.definya.com`)"
        - "traefik.http.routers.rpg-client.entrypoints=websecure"
        - "traefik.http.routers.rpg-client.tls.certresolver=myresolver"
        - "traefik.http.services.rpg-client.loadbalancer.server.port=8080"
      placement:
        constraints:
          - node.labels.accessory == true
    networks:
      - rpg-network
  rpg-docs:
    image: definya/definya-team:docs-latest
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000"]
      interval: 120s
      timeout: 10s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rpg-docs.rule=Host(`docs.definya.com`) || Host(`definya.com`)"
        - "traefik.http.routers.rpg-docs.entrypoints=websecure"
        - "traefik.http.routers.rpg-docs.tls.certresolver=myresolver"
        - "traefik.http.services.rpg-docs.loadbalancer.server.port=3000"
      placement:
        constraints:
          - node.labels.accessory == true
    networks:
      - rpg-network

  rpg-db:
    image: mongo:7.0.0
    command: mongod --port ${MONGO_PORT}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - rpg-db-data:/data/db
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    deploy: # db should be only on the manager node
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ["CMD", "mongosh", "--port", "${MONGO_PORT}", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 30s
      timeout: 15s
      retries: 3
    networks:
      - rpg-network

  rpg-redis:
    image: redis:7.2.0
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - rpg-redis-data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "${REDIS_PORT}"]
    networks:
      - rpg-network
    deploy:
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
      interval: 30s
      timeout: 15s
      retries: 3

networks:
  rpg-network:
    external: true

volumes:
  rpg-db-data:
  rpg-redis-data:
