version: "3.8"

services:
  rpg-api:
    image: definya/definya-team:api-latest
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5002"]
      interval: 60s
      timeout: 30s
      retries: 5
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.api == true
        preferences:
          - spread: node.id
        max_replicas_per_node: 1
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 2
        delay: 10s
      labels:
        # Basic setup for API config
        - traefik.enable=true
        - traefik.http.routers.rpg-api.rule=Host(`na.definya.com`)
        - traefik.http.routers.rpg-api.entrypoints=websecure
        - traefik.http.routers.rpg-api.tls.certresolver=myresolver
        - traefik.http.services.rpg-api-service.loadbalancer.server.port=5002
        - traefik.http.routers.rpg-api.service=rpg-api-service

        # Websockets
        - traefik.http.routers.rpg-api-socket.rule=Host(`na.definya.com`) && Path(`/socket.io/`)
        - traefik.http.routers.rpg-api-socket.entrypoints=websecure
        - traefik.http.routers.rpg-api-socket.tls.certresolver=myresolver
        - traefik.http.services.rpg-api-socket-service.loadbalancer.server.port=5101
        - traefik.http.routers.rpg-api-socket.service=rpg-api-socket-service

        # #  Add sticky session for websockets
        #! Careful because when combined with multi client, this will lead all MC characters to be connected to the same server, compromising load balancer
        - "traefik.http.services.rpg-api-socket-service.loadbalancer.sticky=true"
        - "traefik.http.services.rpg-api-socket-service.loadbalancer.sticky.cookie.name=StickyCookie"
        - "traefik.http.services.rpg-api-socket-service.loadbalancer.sticky.cookie.secure=true"

        - "traefik.http.middlewares.websocket.headers.customrequestheaders.Connection=Upgrade"
        - "traefik.http.middlewares.websocket.headers.customrequestheaders.Upgrade=websocket"
        - "traefik.http.routers.rpg-api-socket.middlewares=websocket@docker"

    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      FORCE_COLOR: "true"
      NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
      NEW_RELIC_APP_NAME: "Definya API"
      RABBITMQ_HOST: "${RABBITMQ_HOST}"
      RABBITMQ_PORT: "${RABBITMQ_PORT}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    networks:
      - rpg-network
    depends_on:
      - rpg-rabbitmq
      - rpg-redis
      - rpg-db

  rpg-npc:
    image: definya/definya-team:api-latest
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5005"]
      interval: 60s
      timeout: 30s
      retries: 5
    environment:
      MICROSERVICE_NAME: "rpg-npc"
      FORCE_COLOR: "true"
      CHOKIDAR_USEPOLLING: "true"
      NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
      NEW_RELIC_APP_NAME: "Definya NPC"
      RABBITMQ_HOST: "${RABBITMQ_HOST}"
      RABBITMQ_PORT: "${RABBITMQ_PORT}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.npc == true
        preferences:
          - spread: node.id
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.3
    networks:
      - rpg-network
    depends_on:
      - rpg-rabbitmq
      - rpg-redis
      - rpg-db

  rpg-pathfinder:
    image: definya/definya-team:rpg-pathfinder-latest
    environment:
      GO111MODULE: "on"
      NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
      NEW_RELIC_APP_NAME: "Definya Pathfinder"
      RABBITMQ_HOST: "${RABBITMQ_HOST}"
      RABBITMQ_PORT: "${RABBITMQ_PORT}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    deploy:
      replicas: 6
      restart_policy:
        condition: on-failure
      placement:
        preferences:
          - spread: node.id
        max_replicas_per_node: 1
      update_config:
        parallelism: 3
        delay: 2s
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.3
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5004/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - rpg-network
    depends_on:
      - rpg-rabbitmq

  rpg-client:
    image: definya/definya-team:client-latest
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 120s
      timeout: 10s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rpg-client.rule=Host(`play.definya.com`)"
        - "traefik.http.routers.rpg-client.entrypoints=websecure"
        - "traefik.http.routers.rpg-client.tls.certresolver=myresolver"
        - "traefik.http.services.rpg-client.loadbalancer.server.port=8080"
      placement:
        constraints:
          - node.labels.accessory == true
    environment:
      NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
      NEW_RELIC_APP_NAME: "Definya Client"
    networks:
      - rpg-network

  rpg-docs:
    image: definya/definya-team:docs-latest
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000"]
      interval: 120s
      timeout: 10s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rpg-docs.rule=Host(`docs.definya.com`) || Host(`definya.com`)"
        - "traefik.http.routers.rpg-docs.entrypoints=websecure"
        - "traefik.http.routers.rpg-docs.tls.certresolver=myresolver"
        - "traefik.http.services.rpg-docs.loadbalancer.server.port=3000"
      placement:
        constraints:
          - node.labels.accessory == true
    environment:
      NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
      NEW_RELIC_APP_NAME: "Definya Docs"
    networks:
      - rpg-network

  rpg-db:
    image: mongo:7.0.0
    command: mongod --port ${MONGO_PORT}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - rpg-db-data:/data/db
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
      NEW_RELIC_APP_NAME: "Definya DB"
    deploy:
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ["CMD", "mongosh", "--port", "${MONGO_PORT}", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 30s
      timeout: 15s
      retries: 3
    networks:
      - rpg-network

  rpg-redis:
    image: redis:7.2.0
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - rpg-redis-data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "${REDIS_PORT}"]
    environment:
      NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
      NEW_RELIC_APP_NAME: "Definya Redis"
    networks:
      - rpg-network
    deploy:
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
      interval: 30s
      timeout: 15s
      retries: 3

  newrelic-infra:
    image: newrelic/infrastructure:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host:ro
    environment:
      NRIA_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
      NRIA_DISPLAY_NAME: "Definya Swarm Node"
    deploy:
      mode: global
    networks:
      - rpg-network

  rpg-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
      RABBITMQ_PLUGINS: "rabbitmq_management"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./environment/rabbit-init.sh:/docker-entrypoint-initdb.d/rabbit-init.sh
      - ./environment/rabbitmq-config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

    networks:
      - rpg-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rpg-rabbitmq.rule=Host(`rabbitmq.definya.com`)"
      - "traefik.http.routers.rpg-rabbitmq.entrypoints=websecure"
      - "traefik.http.routers.rpg-rabbitmq.tls.certresolver=myresolver"
      - "traefik.http.services.rpg-rabbitmq.loadbalancer.server.port=15672"
      - "traefik.http.routers.rpg-rabbitmq.service=rpg-rabbitmq"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  rpg-network:
    external: true

volumes:
  rpg-db-data:
  rpg-redis-data:
  rabbitmq_data:
