# Use the official Node.js 20 image
FROM node:20

# Install system dependencies including Git (which might not be included by default)
RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package files
COPY package.json yarn.lock ./

# Install dependencies using yarn
RUN yarn --frozen-lockfile

# Copy the rest of the application code
COPY . .

# Expose necessary ports
EXPOSE 5002
EXPOSE 5100
EXPOSE 5101

# Set environment variables for New Relic
ENV NEW_RELIC_NO_CONFIG_FILE=true \
    NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true \
    NEW_RELIC_LOG=stdout \
    NEW_RELIC_LOG_LEVEL=error

# Command to run the application
CMD ["yarn", "dev"]
