version: "3"

services:
  rpg-api:
    container_name: rpg-api
    restart: always
    image: definya/definya-team:api-latest
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - rpg-db
      - rpg-redis
    depends_on:
      - rpg-db
      - rpg-redis
    network_mode: bridge
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "$SOCKET_PORT:$SOCKET_PORT"
      # - "$SOCKET_UDP_RANGE" #!COMMENT THIS IN IF USING UDP
    environment:
      FORCE_COLOR: "true"
      VIRTUAL_HOST: ${API_SUBDOMAIN}
      LETSENCRYPT_HOST: ${API_SUBDOMAIN}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}
      VIRTUAL_PORT: ${SERVER_PORT}
      NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
      NEW_RELIC_APP_NAME: "Definya API"
  rpg-pathfinder:
    container_name: rpg-pathfinder
    build:
      context: ./microservices/rpg-pathfinder
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    volumes:
      - ./microservices/rpg-pathfinder:/app
    environment:
      - GO111MODULE=on
    command: air
    networks:
      - rpg-network
  rpg-db:
    container_name: rpg-db
    image: mongo
    restart: always
    command: mongod --port ${MONGO_PORT}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    ports:
      - "$MONGO_PORT:$MONGO_PORT"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    network_mode: bridge

  rpg-redis:
    container_name: rpg-redis
    restart: always
    image: redis:latest
    ports:
      - "$REDIS_PORT:$REDIS_PORT"
    expose:
      - "$REDIS_PORT"
    env_file: .env
    volumes:
      - ./config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf", "--port", "${REDIS_PORT}"]
    network_mode: bridge
