# .air.toml

[build]
  # Command to build the project.
  cmd = "go build -o ./tmp/main"
  
  # Binary file created by above command.
  bin = "tmp/main"
  
  # Working directory.
  dir = "."
  
  # Number of lines in terminal scrollback buffer.
  scrollback = 10000

[watch]
  # Watch for changes in these directories.
  # You can exclude vendor directory or other directories that don't need to be watched.
  dirs = ["."]
  
  # File extensions to watch for changes.
  extensions = ["go", "tpl", "tmpl", "html"]

[log]
  # Customize the log colors.
  level = "debug"

[dev]
  # Exclude these directories from watching.
  exclude_dir = ["vendor", "tmp"]
