# Use a Go base image that includes essential tools for both building and running
FROM golang:1.20

# Set up working directory
WORKDIR /app

# Copy the source code
COPY . .

# Build the Go application
RUN go build -o app .

# Expose the necessary port
EXPOSE 5004

# Run the application binary
CMD ["/app/app"]
