export const CHARACTER_SKULL_AMOUNT_KILLS_NEEDED_TO_RED_SKULL = 3;
export const CHARACTER_SKULL_AMOUNT_KILLS_NEEDED_TO_YELLOW_SKULL = 1;
export const CHARACTER_SKULL_MAX_TIME_UNTIL_UPGRADE_TO_RED_SKULL = 10 * 24 * 60 * 60 * 1000;
export const CHARACTER_SKULL_RED_SKULL_DURATION = 14 * 24 * 60 * 60 * 1000;
export const CHARACTER_SKULL_WHITE_SKULL_DURATION = 15 * 60 * 1000;
export const CHARACTER_SKULL_YELLOW_SKULL_DURATION = 7 * 24 * 60 * 60 * 1000;
