# Premium Account :: Create Items
POST {{baseUrl}}/premium-account/create-item HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "blueprintKey": "wooden-shield",
  "quantity": 1,
  "characterId": "658a45a606449b00345d8ee1" 
}

###

# Premium Account :: Create Extra Depot Slots
POST {{baseUrl}}/premium-account/create-extra-depot-slots HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "characterId": "6549765f4ce996004faaa311",
  "depotCity": "ilya",
  "slotQtyToAdd": 40
}

###
