# Premium Account :: Create Items
POST {{baseUrl}}/premium-account/create-item HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "blueprintKey": "greater-mana-potion",
  "quantity": 100,
  "characterId": "6516df4e6f26650064cdee41" 
}

###

# Premium Account :: Create Extra Depot Slots
POST {{baseUrl}}/premium-account/create-extra-depot-slots HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "characterId": "6549765f4ce996004faaa311",
  "depotCity": "ilya",
  "slotQtyToAdd": 40
}

###
