# Premium Account :: Create Items
POST {{baseUrl}}/premium-account/create-item HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "blueprintKey": "wooden-sword",
  "quantity": 1,
  "characterId": "66b56a010fcbba00654d011c" 
}

###

# Premium Account :: Create Extra Depot Slots
POST {{baseUrl}}/premium-account/create-extra-depot-slots HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "characterId": "65dbb3773658bd0035038e14",
  "depotCity": "ilya",
  "slotQtyToAdd": 40
}

###

# Activate Premium Account
POST {{baseUrl}}/premium-account/activate HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "email": "wallacehm22@gmail.com",
  "accountType": "silver"
}

###

# Deactivate Premium Account
POST {{baseUrl}}/premium-account/deactivate HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "email": "user@example.com"
}

