### Scripts :: Adjust attack speed
GET {{baseUrl}}/scripts/initial-coordinates HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Scripts :: Remove marketplace junk
GET {{baseUrl}}/scripts/clean-marketplace HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Scripts :: Clean junk items
GET {{baseUrl}}/scripts/cleanup/items HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Scripts :: Adjust base speed
GET {{baseUrl}}/scripts/adjust-speed HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Scripts :: Remove redis junk
GET {{baseUrl}}/scripts/cleanup/redis/craftable-item-ingredients HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Scripts :: Cleanup character user cache
GET {{baseUrl}}/scripts/cleanup-character-user-cache/6554ce7c58ce91005ebc3d8c HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Scripts :: Adjust item minRequirements
GET {{baseUrl}}/scripts/update-items-min-requirements HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Scripts :: Update farming skills
GET {{baseUrl}}/scripts/update-farming-skills HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Scripts :: Fix depot ownership
GET {{baseUrl}}/scripts/fix-depot-ownership HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Scripts :: Dump users email on txt
GET {{baseUrl}}/scripts/users-emails-dump HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json
  

### Scripts :: Farmland depot fix
GET {{baseUrl}}/scripts/farmland-depot-fix HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json
  