### Scripts :: Adjust attack speed
GET {{baseUrl}}/scripts/initial-coordinates HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Scripts :: Remove marketplace junk
GET {{baseUrl}}/scripts/clean-marketplace HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Scripts :: Clean junk items
GET {{baseUrl}}/scripts/cleanup/items HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Scripts :: Adjust base speed
GET {{baseUrl}}/scripts/adjust-speed HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Scripts :: Remove redis junk
GET {{baseUrl}}/scripts/cleanup/redis/blueprint-spells HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Scripts :: Cleanup character user cache
GET {{baseUrl}}/scripts/cleanup-character-user-cache/6554ce7c58ce91005ebc3d8c HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json
