services:
  startup-postgresql:
    container_name: startup-postgresql
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - startup-network
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c '\q'
      interval: 2s
      timeout: 10s
      retries: 5

  prisma-migrations:
    image: node:18
    container_name: prisma-migrations
    working_dir: /app
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@startup-postgresql:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
    volumes:
      - ./:/app
    depends_on:
      startup-postgresql:
        condition: service_healthy
    command: >
      sh -c "
      npm install -g prisma &&
      npx prisma generate &&
      npx prisma migrate dev --name init
      "
    networks:
      - startup-network
    restart: "no"
volumes:
  postgres_data:
