services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRESQL_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRESQL_PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - startup-postgresql
    networks:
      - startup-network

volumes:
  postgres_data:
